# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
#  vmImage: ubuntu-latest
  vmImage: windows-2022

steps:
#- script: echo Hello, world!
- script: echo Pipeline scripted
  displayName: 'Pipeline scripted deployment environments'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Dallas Azure Innovation Lab(dac730c2-4027-48aa-b9ea-c423e0e228b4)'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      iex "& { $(irm https://aka.ms/DevCenter/Install-DevCenterCli.ps1 ) }"
      $params = "{ 'location': 'eastus2' }"
      az devcenter dev environment create --dev-center-name  devcenter-contoso-eus2 --project-name web-app-basic -n pipeline00 --environment-type Dev --catalog-item-name WebApp --catalog-name community-examples --parameters $params
#    arguments: '--dev-center-name  devcenter-contoso-eus2 --project-name web-app-basic -n pipeline --environment-type Dev --catalog-item-name WebApp --catalog-name community-examples --parameters $params'